// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD9C-7XaoAnM6Vkt9Bx4e9lZhY3pBkKvM',
    appId: '1:586613437936:web:87a67b933f7dbe18fc1935',
    messagingSenderId: '586613437936',
    projectId: 'odev2final',
    authDomain: 'odev2final.firebaseapp.com',
    storageBucket: 'odev2final.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAV8YU5-gnGUWpti13E8qYgcbs6veVtuEw',
    appId: '1:586613437936:android:a94acc5e9ea80f7ffc1935',
    messagingSenderId: '586613437936',
    projectId: 'odev2final',
    storageBucket: 'odev2final.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD9C-7XaoAnM6Vkt9Bx4e9lZhY3pBkKvM',
    appId: '1:586613437936:web:4119c2a5a10a3499fc1935',
    messagingSenderId: '586613437936',
    projectId: 'odev2final',
    authDomain: 'odev2final.firebaseapp.com',
    storageBucket: 'odev2final.firebasestorage.app',
  );
}
